const HOUR=36e5,FIVE_DAYS=432e6,SAVE_KEY="mogu-pet-v1";
const DECOR=[{id:"ring",icon:"🍩",name:"甜甜圈泳圈",price:4,className:"decor-ring"},{id:"ball",icon:"🏖️",name:"海灘球",price:7,className:"decor-ball"},{id:"plant",icon:"🌴",name:"迷你椰子樹",price:12,className:"decor-plant"},{id:"light",icon:"✨",name:"星星池燈",price:18,className:"decor-light"}];
const FOODS=[{icon:"🐟",name:"小魚"},{icon:"🦐",name:"甜蝦"},{icon:"🦑",name:"魷魚"}];
const $=id=>document.getElementById(id);
const fresh=()=>({satiety:35,affection:20,coins:1000,lastFedAt:Date.now(),lastSeenAt:Date.now(),owned:[],active:[],dead:false,starterCoinsGranted:1});
let pet=fresh(),mode="home",reactionTimer,audio;
try{const saved=localStorage.getItem(SAVE_KEY);if(saved){const previous=JSON.parse(saved),now=Date.now(),hours=Math.max(0,Math.floor((now-previous.lastSeenAt)/HOUR)),starter=previous.starterCoinsGranted!==1;pet={...previous,satiety:Math.max(0,previous.satiety-hours*.75),affection:Math.max(0,previous.affection-hours*.18),coins:starter?Math.max(1000,previous.coins+hours):previous.coins+hours,lastSeenAt:now,dead:previous.dead||now-previous.lastFedAt>=FIVE_DAYS,starterCoinsGranted:1};$("notice").textContent=pet.dead?"你太久沒回來了……":starter?"新手禮物：1000 枚海豹幣已送達！":hours?`離線 ${hours} 小時，獲得 ${hours} 枚海豹幣！`:"小海豹正在等你～"}}catch{pet=fresh()}
function save(){pet.lastSeenAt=Date.now();localStorage.setItem(SAVE_KEY,JSON.stringify(pet))}
function stage(){return pet.satiety<20?1:pet.satiety<40?2:pet.satiety<70?3:pet.satiety<90?4:5}
function mood(){return pet.dead?"永遠睡著了":pet.satiety<20?"肚子咕嚕咕嚕……":pet.affection>75?"最喜歡你了！":pet.satiety>80?"飽飽的，好幸福～":"今天要一起玩什麼？"}
function render(){
 const s=stage();$("coins").textContent=Math.floor(pet.coins);$("satiety-text").textContent=`${Math.round(pet.satiety)}%`;$("affection-text").textContent=`${Math.round(pet.affection)}%`;$("satiety-bar").style.width=`${pet.satiety}%`;$("affection-bar").style.width=`${pet.affection}%`;$("speech").textContent=mood();$("seal-art").src=`assets/seal-stage-${s}.webp`;$("seal").classList.forEach(c=>{if(c.startsWith("stage-"))$("seal").classList.remove(c)});$("seal").classList.add(`stage-${s}`);$("pool").className=`pool-scene mode-${mode}`;$("decorations").innerHTML=DECOR.filter(x=>pet.active.includes(x.id)).map(x=>`<span class="pool-decor ${x.className}">${x.icon}</span>`).join("");document.querySelectorAll(".bottom-nav button").forEach(b=>b.classList.toggle("active",b.dataset.mode===mode));$("dead-overlay").hidden=!pet.dead;renderDrawer();save()
}
function renderDrawer(){
 const d=$("drawer");d.classList.toggle("closed",mode==="home");if(mode==="home")return;
 if(mode==="pet")d.innerHTML='<div class="interaction-card"><span class="big-hand">🫳</span><div><small>摸摸時間</small><h2>輕點海豹摸摸牠</h2><p>每次摸摸，好感度增加 5%</p></div></div>';
 if(mode==="feed")d.innerHTML='<div class="drawer-title"><div><small>開飯啦</small><h2>今天想吃哪一個？</h2></div><span>每份 +10% 飽足度</span></div><div class="food-grid">'+FOODS.map((x,i)=>`<button data-food="${i}"><b>${x.icon}</b><span>${x.name}</span><small>飽足度 +10%</small></button>`).join("")+"</div>";
 if(mode==="shop")d.innerHTML='<div class="drawer-title"><div><small>泳池小屋</small><h2>佈置舒服的家</h2></div><span>每離線 1 小時獲得 1 幣</span></div><div class="shop-grid">'+DECOR.map((x,i)=>{const owned=pet.owned.includes(x.id),active=pet.active.includes(x.id);return`<button data-decor="${i}"><b>${x.icon}</b><span>${x.name}</span><small>${owned?(active?"使用中・點擊收起":"已擁有・點擊擺上"):`🪙 ${x.price}`}</small></button>`}).join("")+"</div>";
 d.querySelectorAll("[data-food]").forEach(b=>b.onclick=()=>feed(FOODS[+b.dataset.food]));d.querySelectorAll("[data-decor]").forEach(b=>b.onclick=()=>buy(DECOR[+b.dataset.decor]))
}
function sound(kind){audio??=new AudioContext();if(audio.state==="suspended")audio.resume();const now=audio.currentTime,g=audio.createGain(),notes=kind==="eat"?[220,110,520]:kind==="pet"?[520,720]:[700,980];g.connect(audio.destination);notes.forEach((f,i)=>{const o=audio.createOscillator();o.type=i?"sine":"triangle";o.frequency.setValueAtTime(f,now+i*.055);o.connect(g);o.start(now+i*.055);o.stop(now+.12+i*.055)});g.gain.setValueAtTime(.0001,now);g.gain.exponentialRampToValueAtTime(.13,now+.018);g.gain.exponentialRampToValueAtTime(.0001,now+.3)}
function react(kind,icon){$("seal").classList.remove("eat","pet");void $("seal").offsetWidth;$("seal").classList.add(kind);$("reaction-icon").textContent=icon;$("reaction-icon").hidden=false;clearTimeout(reactionTimer);reactionTimer=setTimeout(()=>{$("reaction-icon").hidden=true;$("seal").classList.remove(kind)},850)}
function feed(food){if(pet.dead)return;pet.satiety=Math.min(100,pet.satiety+10);pet.affection=Math.min(100,pet.affection+1);pet.lastFedAt=Date.now();$("notice").textContent=`${food.name}吃光光！飽足度 +10%`;react("eat",food.icon);sound("eat");render()}
function petSeal(){if(pet.dead||mode!=="pet")return;pet.affection=Math.min(100,pet.affection+5);$("notice").textContent="摸摸成功！好感度 +5%";react("pet","♥");sound("pet");render()}
function buy(item){if(pet.owned.includes(item.id)){pet.active=pet.active.includes(item.id)?pet.active.filter(x=>x!==item.id):[...pet.active,item.id];$("notice").textContent=pet.active.includes(item.id)?`擺上${item.name}！`:`收起${item.name}`;render();return}if(pet.coins<item.price){$("notice").textContent="海豹幣不夠，再離線休息一下吧～";return}pet.coins-=item.price;pet.owned.push(item.id);pet.active.push(item.id);$("notice").textContent=`買到${item.name}了！`;sound("coin");render()}
document.querySelectorAll(".bottom-nav button").forEach(b=>b.onclick=()=>{mode=mode===b.dataset.mode?"home":b.dataset.mode;render()});$("seal").onclick=petSeal;$("adopt").onclick=()=>{pet=fresh();mode="home";$("notice").textContent="新的小海豹來到泳池了，記得照顧牠！";render()};
setInterval(()=>{if(!pet.dead){pet.satiety=Math.max(0,pet.satiety-.0125);pet.affection=Math.max(0,pet.affection-.003);pet.dead=Date.now()-pet.lastFedAt>=FIVE_DAYS;render()}},6e4);render();
